### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by joe0327** [ppaanngggg/KCFTracker#1]
你好，我在使用你的程序的时候，怎么每次到patch = fhog::fhog(patch, params.binSize);这一句的时候就报错？请问一下  你可以完整的编译通过这个程序么？你用的是什么配置呢？谢谢！

**Comment by ppaanngggg** [comment]
sorry，这个fhog的代码我是从DPM那里提取出来的，好像是有点问题，你尝试一下4之类的binSize值。我这里默认的配置不会出错的。你考虑下是不是别的问题

**Comment by joe0327** [comment]
哦  还有一个问题   float im[dims[0] \* dims[1] \* 3];这个定义也会报错的呀  你可以直接编译通过 ？

**Comment by ppaanngggg** [comment]
啊，编译器选项问题吧，我没问题的，可能要c99的特性

**Comment by liuqunzhong** [comment]
new就可以了。float\* im = new float(d0_d1_3);

**Comment by ppaanngggg** [comment]
那记得free，记得检查im是否是null即可，都一样的

**Comment by joe0327** [comment]
嗯  你现在有可编译通过的版本么？能不能把你的工程update一次？额  我想先跑着试一下

**Comment by ppaanngggg** [comment]
sorry，我现在没有，很久没维护这个了

**Comment by joe0327** [comment]
哦  好吧  我自己调试一下  谢谢啦  没想到你真的在线

**Comment by liuqunzhong** [comment]
调试一下 确实是可以跑起来的
