### ISSUE TITLE
main

### ISSUE THREAD

**Issue by zrr1991** [ppaanngggg/KCFTracker#2]
Dear Author:
I debug your code, may be our system are different, I can't pass compile, and I find there is no 'main function', so how can I do continuely. Would you mind provide me a quick start guide? Thank you .

**Comment by ppaanngggg** [comment]
so you need a demo?

**Comment by chk0905** [comment]
i don't know how to operate this code. 
if possible, could you give me a demo code?
thank you.

**Comment by ppaanngggg** [comment]
I will fix it according to #3
